### PR TITLE
Introduce a BlueSky bot variant.

### PR DESCRIPTION
**Pull request by theFestest**
This is a draft of a bot for BlueSky (https://bsky.app/).

Requires:
- BlueSky Account (I would be happy to provide an invite code if needed)
- App Password (generated in-app)
- atproto python package (as per requirements.txt)
- initial conditions file and video file on the filesystem

Note that this is a draft as BlueSky does not currently support video/gif posts but has them both on the roadmap:
- video: https://github.com/bluesky-social/social-app/issues/1052
- gif: https://github.com/bluesky-social/social-app/issues/1047

If this bot is something that would be interesting, I will be happy to come back to touch this up once that media support is added.

Otherwise, this should be testable using image files in the meantime.

### CODE REVIEW

**Comment by kirklong** [comment]
Hi @theFestest -- thanks for submitting this! I'll leave this pending for now, but yes, if/when BlueSky allows for videos/gifs would love to use this and port the app there. I don't currently have a BlueSky account but if you can provide an invite code I'll reserve the handle for the bot.

**Comment by sergiobarriel** [comment]
Here some invitation codes:

bsky-social-rj6nl-hbgon
bsky-social-btifp-xi3s7

**Comment by kirklong** [comment]
Great, thanks @sergiobarriel! I've reserved the bot's handle on BlueSky using the first code.

**Comment by theFestest** [comment]
It took almost a year but video support has arrived on BlueSky (with gifs coming soon)!

I've updated this to use the new video API and simplified things a bit.

I tested the script myself just a bit ago [here](https://bsky.app/profile/thefeste.st/post/3l45lv3yvpg26) with the following output:
```
$ python BlueSkyUpload.py
Logged in as:  theFestest
Attempt 1 posting to BlueSky...
Sending post with text:
video api test
Posted to BlueSky!
```

Please let me know if you have any trouble -- happy to help!

**Comment by kirklong** [comment]
Somehow I just saw this -- thanks so much for the update! I will implement this ASAP :)

**Comment by kirklong** [comment]
It's not properly attaching the video and I'm not sure why (not returning an error either). Have to run to meetings rest of day today but will take a deeper look and try to debug tomorrow morning.

**Pull request merged**
